#!/usr/bin/env node
/**
 * Copies the canonical ELC Conference 2027 offer into this (public, self-contained) repo.
 *
 *   canonical: ~/ai/business/elcc/data/conference-offer-2027.json  (private elcc-content repo;
 *              also read by the /partner/ page and the offer API)
 *   copy:      src/data/offer-2027.ts  (committed; what wrangler bundles and tsc compiles)
 *
 * Runs before every build and deploy. When the canonical file is absent (CI, a fresh clone),
 * it does nothing and the committed copy is used. Keys starting with "_" are internal notes
 * (source paths) and are dropped from the copy; everything else is copied verbatim.
 *
 *   node scripts/sync-offer.mjs           copy if changed
 *   node scripts/sync-offer.mjs --check   exit 1 if the copy differs from the canonical file
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const canonical = process.env.ELC_OFFER_JSON ?? join(homedir(), "ai/business/elcc/data/conference-offer-2027.json");
const target = join(root, "src/data/offer-2027.ts");

if (!existsSync(canonical)) {
	console.log(`sync-offer: ${canonical} not found, using the committed src/data/offer-2027.ts`);
	process.exit(0);
}

const strip = (v) =>
	Array.isArray(v)
		? v.map(strip)
		: v && typeof v === "object"
			? Object.fromEntries(Object.entries(v).filter(([k]) => !k.startsWith("_")).map(([k, x]) => [k, strip(x)]))
			: v;

const data = strip(JSON.parse(readFileSync(canonical, "utf8")));
const body = `// GENERATED by scripts/sync-offer.mjs from ~/ai/business/elcc/data/conference-offer-2027.json.
// Do not edit by hand: change the canonical JSON, then run \`node scripts/sync-offer.mjs\`.
// Same data as https://www.elc-conference.io/partner/ (prices EUR, ex VAT).
const OFFER_2027 = ${JSON.stringify(data, null, "\t")};

export default OFFER_2027;
`;

const current = existsSync(target) ? readFileSync(target, "utf8") : "";
if (process.argv.includes("--check")) {
	if (current !== body) {
		console.error("sync-offer: src/data/offer-2027.ts is out of date. Run: node scripts/sync-offer.mjs");
		process.exit(1);
	}
	console.log("sync-offer: copy matches the canonical offer");
	process.exit(0);
}
if (current === body) {
	console.log("sync-offer: copy already up to date");
} else {
	writeFileSync(target, body);
	console.log(`sync-offer: wrote src/data/offer-2027.ts (offer version ${data.version}, updated ${data.updated})`);
}
