// GENERATED by scripts/sync-offer.mjs from ~/ai/business/elcc/data/conference-offer-2027.json.
// Do not edit by hand: change the canonical JSON, then run `node scripts/sync-offer.mjs`.
// Same data as https://www.elc-conference.io/partner/ (prices EUR, ex VAT).
const OFFER_2027 = {
	"version": "2027.1",
	"updated": "2026-10-01",
	"currency": "EUR",
	"vat": "Prices are ex VAT.",
	"event": {
		"name": "ELC Conference 2027",
		"when": "April 2027 (exact date to be announced)",
		"where": "Prague, Czech Republic",
		"format": "One day: main-stage talks, hands-on workshops, a mentoring zone",
		"organiser": "Engineering Leaders Community (ELC)",
		"principle": "Speakers are picked for what they built. A paid slot on the main stage does not exist. Partners' speakers can apply through the call for speakers and go through the same selection."
	},
	"proof": {
		"attendees_2026": "350+",
		"attendees_target_2027": "600+ (target)",
		"rating": "4.8",
		"companies_2026": 134,
		"programme_2026": {
			"talks": 14,
			"workshops": 15,
			"speakers": 40,
			"mentors": 11
		},
		"community_members": "3,300+",
		"manager_and_above": "69%",
		"newsletter_opens_per_issue": "1,500+",
		"newsletter_subscribers": "2,900+",
		"meetups_since_2019": "40+",
		"cities": [
			"Prague",
			"Brno",
			"Bratislava",
			"Kraków"
		],
		"partner_hires_per_month": 2.7,
		"attendee_mix_2025": [
			{
				"group": "Engineering leadership",
				"share": 43
			},
			{
				"group": "Senior ICs and tech leads",
				"share": 22.6
			},
			{
				"group": "Founders and executives",
				"share": 16.6
			},
			{
				"group": "Product and delivery",
				"share": 8.9
			},
			{
				"group": "Specialists and cross-functional",
				"share": 8.9
			}
		],
		"speaker_companies": [
			"SpaceX",
			"Superhuman",
			"Netflix",
			"Stripe",
			"Meta",
			"Microsoft",
			"Financial Times",
			"Apify"
		],
		"past_partners": [
			"ČSOB",
			"Microsoft",
			"Eurowag",
			"Make",
			"Apify",
			"Bloomreach",
			"Applifting"
		],
		"speaker_wall": [
			{
				"company": "SpaceX",
				"logo": "speaker-spacex.svg",
				"speaker": "David Pavlik",
				"role": "CTO, Rohlik Group · ex-SpaceX",
				"year": 2025,
				"photo": "david-pavlik.webp"
			},
			{
				"company": "Superhuman",
				"logo": "speaker-superhuman.webp",
				"speaker": "Rizwan Iqbal",
				"role": "Director of Engineering, Superhuman",
				"year": 2026,
				"photo": "rizwan-iqbal.webp"
			},
			{
				"company": "Netflix",
				"logo": "speaker-netflix.webp",
				"speaker": "Michal Matyjek",
				"role": "Sr. Engineering Manager, Netflix",
				"year": 2026,
				"photo": "michal-matyjek.webp"
			},
			{
				"company": "Stripe",
				"logo": "speaker-stripe.webp",
				"speaker": "Aleodor Tabarcea",
				"role": "Engineering Manager, Stripe",
				"year": 2026,
				"photo": "aleodor-tabarcea.webp"
			},
			{
				"company": "Meta",
				"logo": "speaker-meta.webp",
				"speaker": "David Teodorescu",
				"role": "Senior Product Designer, Meta",
				"year": 2026,
				"photo": "david-teodorescu.webp"
			},
			{
				"company": "Microsoft",
				"logo": "speaker-microsoft.webp",
				"speaker": "Vojta Vondra",
				"role": "Partner Director of Engineering, Microsoft",
				"year": 2026,
				"photo": "vojta-vondra.webp"
			},
			{
				"company": "Financial Times",
				"logo": "speaker-financial-times.webp",
				"speaker": "Tatiana Stantonian",
				"role": "Principal Engineer, Financial Times",
				"year": 2026,
				"photo": "tatiana-stantonian.webp"
			},
			{
				"company": "Apify",
				"logo": "speaker-apify.webp",
				"speaker": "Jan Zenisek",
				"role": "VP of Product, Apify",
				"year": 2026,
				"photo": "jan-zenisek.webp"
			}
		],
		"headline_claim": "8 in 10 people in the room lead AI agents, people or technology.",
		"headline_claim_basis": "#ELC2025 attendee mix: engineering leadership 43.0% + senior ICs and tech leads 22.6% + founders and executives 16.6% = 82.2%."
	},
	"packages": [
		{
			"id": "partner",
			"name": "Partner",
			"price": 38000,
			"seats": 2,
			"tagline": "The first to sign is the main partner of the day.",
			"best_for": [
				"hiring",
				"growing your own leaders",
				"being the name on the day"
			],
			"includes": [
				"A workshop or mentor slot for your leader; your speaker can apply for the main stage (same selection as everyone else)",
				"14 tickets",
				"10 mentoring sessions with Marian on technical leadership and AI",
				"Direct access to 3,300+ community members",
				"An ELC meetup for 100+ leaders in your office in February 2027",
				"3 months of social posts and videos, a podcast episode",
				"Booth in the Experience Zone and seats at the speakers' dinner on request",
				"Listed on the website and partner boards"
			]
		},
		{
			"id": "luminary",
			"name": "Luminary",
			"price": 20000,
			"seats": 3,
			"tagline": "For visibility among engineering leaders.",
			"best_for": [
				"brand visibility"
			],
			"includes": [
				"10 tickets",
				"Booth in the Experience Zone",
				"Dedicated newsletter to 2,900+ subscribers",
				"2 seats at the speakers' dinner",
				"Listed on the website and partner boards"
			]
		},
		{
			"id": "navigator",
			"name": "Navigator",
			"price": 12000,
			"seats": 6,
			"tagline": "For hiring and employer brand.",
			"best_for": [
				"hiring",
				"employer brand"
			],
			"includes": [
				"5 tickets",
				"Booth in the Experience Zone",
				"1 month on the ELC Jobs platform",
				"1 seat at the speakers' dinner",
				"Listed on the website and partner boards"
			]
		},
		{
			"id": "pioneer",
			"name": "Pioneer",
			"price": 5000,
			"seats": null,
			"tagline": "For startups meeting early adopters.",
			"best_for": [
				"startups",
				"early adopters"
			],
			"includes": [
				"2 tickets",
				"Partner spotlight in the newsletter",
				"Listed on the website and partner boards"
			]
		}
	],
	"addons": [
		{
			"id": "speakers-dinner",
			"name": "Speakers' dinner",
			"price": 5000,
			"limit": 1,
			"summary": "Host the evening with the speakers and partners.",
			"includes": [
				"Your welcome word at the dinner",
				"Your name on the invitation and in the programme"
			]
		},
		{
			"id": "afterparty",
			"name": "Afterparty",
			"price": 6000,
			"limit": 1,
			"summary": "Your name on the party after the last talk.",
			"includes": [
				"Your welcome word at the party",
				"Your name in the programme and on site"
			]
		},
		{
			"id": "roundtable",
			"name": "Leadership roundtable",
			"price": 6000,
			"limit": 1,
			"summary": "A closed table of engineering leaders on your topic.",
			"includes": [
				"We invite the leaders and host the table",
				"A room and a listing in the programme"
			]
		},
		{
			"id": "partner-workshop",
			"name": "Partner workshop",
			"price": 4000,
			"limit": 1,
			"summary": "Your workshop, labelled as a partner session, off the main stage.",
			"includes": [
				"Room and AV",
				"Promotion on the web and in the programme",
				"Registration, and the contacts of attendees who opt in"
			]
		}
	],
	"pricing_rules": {
		"addons_require_package": true,
		"second_addon_discount": {
			"percent": 25,
			"rule": "With two or more add-ons, the second most expensive add-on is 25% off. Other add-ons are full price."
		},
		"early_sign_discount": {
			"percent": 10,
			"deadline": "2026-12-31",
			"rule": "10% off the whole order (package + add-ons, after the add-on discount) if the contract is signed by 31 December 2026."
		},
		"renewal": "2026 partners get a renewal price, agreed on a call. Not computed automatically.",
		"attendee_lists": "ELC does not share attendee lists. A partner workshop includes the contacts of attendees who register for it and opt in."
	},
	"links": {
		"partner_page": "https://www.elc-conference.io/partner/",
		"deck_pdf": "https://www.elc-conference.io/partner/ELC-Conference-2027-Partner-Deck.pdf",
		"one_pager_pdf": "https://www.elc-conference.io/partner/ELC-Conference-2027-Partner-One-Pager.pdf",
		"gallery": "https://www.elc-conference.io/gallery/",
		"speakers_2026": "https://www.elc-conference.io/speakers",
		"recap_2025": "https://www.elc-conference.io/2025",
		"call_for_speakers": "https://www.elc-conference.io/cfp",
		"youtube_channel": "https://www.youtube.com/@engineeringleaders/videos",
		"videos": [
			{
				"id": "JdwHxXgqEXQ",
				"title": "Become a Partner of ELC 27"
			},
			{
				"id": "6RR2s8LsIp4",
				"title": "ELC 26 Aftermovie"
			},
			{
				"id": "iEo4g0I0eiY",
				"title": "ELC Conference 2026 Official Trailer"
			},
			{
				"id": "HGTIw0y_ANM",
				"title": "#ELC2025 Aftermovie"
			}
		],
		"book_a_call": "https://www.elc.space/meet-marian"
	},
	"contacts": [
		{
			"name": "Marian Kamenišťák",
			"role": "Founder, ELC",
			"email": "marian@engineeringleaders.io"
		},
		{
			"name": "Mirka Hofmanová",
			"role": "Conference producer, ELC",
			"email": "mirka@engineeringleaders.io"
		}
	]
};

export default OFFER_2027;
